In [1]:
###########################################
# --------------------------------------- #
#      Sistema de resortes acoplados      #
# --------------------------------------- #
#
# __________Jessica Isamar Uriarte Garcia #
# ____________________________ Abril 2018 #
###########################################

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from scipy.integrate import odeint
from numpy import loadtxt
from pylab import figure, plot, xlabel, grid, hold, legend, title, savefig
from matplotlib.font_manager import FontProperties

In [2]:
################
## Ejemplo 2.1 #
################


def vectorfield(w, t, p):
    """
    Defines the differential equations for the coupled spring-mass system.

    Arguments:
        w :  vector of the state variables:
                  w = [x1,y1,x2,y2]
        t :  time
        p :  vector of the parameters:
                  p = [m1,m2,k1,k2,L1,L2,b1,b2]
    """
    x1, y1, x2, y2 = w
    m1, m2, k1, k2, L1, L2, b1, b2 = p

    # Create f = (x1',y1',x2',y2'):
    f = [y1,
         (-b1 * y1 - k1 * (x1 - L1) + k2 * (x2 - x1 - L2)) / m1,
         y2,
         (-b2 * y2 - k2 * (x2 - x1 - L2)) / m2]
    return f

In [3]:
# Use ODEINT to solve the differential equations defined by the vector field


# Parameter values
# Masses:
m1 = 1.0
m2 = 1.0
# Spring constants
k1 = 6.0
k2 = 4.0
# Natural lengths
L1 = 0.0
L2 = 0.0
# Friction coefficients
b1 = 0.0
b2 = 0.0

# Initial conditions
# x1 and x2 are the initial displacements; y1 and y2 are the initial velocities
x1 = 1.0
y1 = 0.0
x2 = 2.0
y2 = 0.0

# ODE solver parameters
abserr = 1.0e-8
relerr = 1.0e-6
stoptime = 50
numpoints = 500

# Create the time samples for the output of the ODE solver.
t = [stoptime * float(i) / (numpoints - 1) for i in range(numpoints)]

# Pack up the parameters and initial conditions:
p = [m1, m2, k1, k2, L1, L2, b1, b2]
w0 = [x1, y1, x2, y2]

# Call the ODE solver.
wsol = odeint(vectorfield, w0, t, args=(p,),
              atol=abserr, rtol=relerr)

with open('two_springs.dat', 'w') as f:
    # Print & save the solution.
    for t1, w1 in zip(t, wsol):
        print  ( t1, w1[0], w1[1], w1[2], w1[3], file=f )

In [8]:
# Plot the solution that was generated

t, x1, xy, x2, y2 = loadtxt('two_springs.dat', unpack=True)
lw = 1

figure(1, figsize=(6, 4.5))
plot(t, x1, 'c', linewidth=lw)
plot(t, x2, 'b', linewidth=lw)
title('Plot of x1 and x2 showing synchronized motion')
legend((r'$x_1$', r'$x_2$'))
xlabel('t')
grid(True)
savefig('ejem2.1_plot.png', dpi=100)

In [9]:
figure(2, figsize=(6, 4.5))
plot(x1, x2, 'b', linewidth=lw)
grid(True)
title('x1 versus x2')
legend((r'$x_1$', r'$x_2$'))
savefig('ejem2.1_plot2.png', dpi=100)

In [6]:
print(wsol)

[[ 1.          0.          2.          0.        ]
 [ 0.98997671 -0.1997308   1.97995342 -0.39946159]
 [ 0.9601082  -0.39545787  1.9202164  -0.79091574]
 ..., 
 [ 0.2556686  -1.36713343  0.51133719 -2.73426686]
 [ 0.11657659 -1.4044951   0.23315318 -2.80899019]
 [-0.02485232 -1.41370119 -0.04970465 -2.82740238]]


In [10]:
figure(3, figsize=(6, 4.5))
plot(x1,xy, 'c', linewidth=lw)
plot(x2,y2, 'b', linewidth=lw)
title('Phase Portraits for x1 y x2 ')
grid(True)
legend((r'$x_1$', r'$x_2$'), prop=FontProperties(size=10))
savefig("ejem2.1_plot3.png", dpi=100)